---
output: word_document
---
Bringing Libraries 
```{r, echo=TRUE}
library(lattice); library(ggplot2); library(caret); library(randomForest); library(rpart); library(rpart.plot); library(RColorBrewer); library(rattle)
```

Setting Seed
```{r, echo=TRUE}
set.seed(12345)
```

Loading Data
```{r,echo=TRUE}
trainUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
training <- read.csv(url(trainUrl), na.strings=c("NA","#DIV/0!",""))
testing <- read.csv(url(testUrl), na.strings=c("NA","#DIV/0!",""))
```

Partitioning
```{r, echo=TRUE}
inTrain <- createDataPartition(y=training$classe, p=0.6, list=FALSE)
myTraining <- training[inTrain, ]; myTesting <- training[-inTrain, ]
dim(myTraining); dim(myTesting)
```

Cleaning the data
```{r, echo=TRUE}
myDataNZV <- nearZeroVar(myTraining, saveMetrics=TRUE)
```

```{r, echo=TRUE}
myNZVvars <- names(myTraining) %in% c("new_window", "kurtosis_roll_belt", "kurtosis_picth_belt",
"kurtosis_yaw_belt", "skewness_roll_belt", "skewness_roll_belt.1", "skewness_yaw_belt",
"max_yaw_belt", "min_yaw_belt", "amplitude_yaw_belt", "avg_roll_arm", "stddev_roll_arm",
"var_roll_arm", "avg_pitch_arm", "stddev_pitch_arm", "var_pitch_arm", "avg_yaw_arm",
"stddev_yaw_arm", "var_yaw_arm", "kurtosis_roll_arm", "kurtosis_picth_arm",
"kurtosis_yaw_arm", "skewness_roll_arm", "skewness_pitch_arm", "skewness_yaw_arm",
"max_roll_arm", "min_roll_arm", "min_pitch_arm", "amplitude_roll_arm", "amplitude_pitch_arm",
"kurtosis_roll_dumbbell", "kurtosis_picth_dumbbell", "kurtosis_yaw_dumbbell", "skewness_roll_dumbbell",
"skewness_pitch_dumbbell", "skewness_yaw_dumbbell", "max_yaw_dumbbell", "min_yaw_dumbbell",
"amplitude_yaw_dumbbell", "kurtosis_roll_forearm", "kurtosis_picth_forearm", "kurtosis_yaw_forearm",
"skewness_roll_forearm", "skewness_pitch_forearm", "skewness_yaw_forearm", "max_roll_forearm",
"max_yaw_forearm", "min_roll_forearm", "min_yaw_forearm", "amplitude_roll_forearm",
"amplitude_yaw_forearm", "avg_roll_forearm", "stddev_roll_forearm", "var_roll_forearm",
"avg_pitch_forearm", "stddev_pitch_forearm", "var_pitch_forearm", "avg_yaw_forearm",
"stddev_yaw_forearm", "var_yaw_forearm")
myTraining <- myTraining[!myNZVvars]
dim(myTraining)
```

```{r, echo=TRUE}
myTraining <- myTraining[c(-1)]
```

```{r, echo=TRUE}
trainingV3 <- myTraining #creating another subset to iterate in loop
for(i in 1:length(myTraining)) { #for every column in the training dataset
        if( sum( is.na( myTraining[, i] ) ) /nrow(myTraining) >= .6 ) { #if n?? NAs > 60% of total observations
        for(j in 1:length(trainingV3)) {
            if( length( grep(names(myTraining[i]), names(trainingV3)[j]) ) ==1)  { #if the columns are the same:
                trainingV3 <- trainingV3[ , -j] #Remove that column
            }   
        } 
    }
}
dim(trainingV3)

```

```{r,echo=TRUE}
myTraining <- trainingV3
rm(trainingV3)
```

```{r, echo=TRUE}
clean1 <- colnames(myTraining)
clean2 <- colnames(myTraining[, -58]) 
myTesting <- myTesting[clean1]
testing <- testing[clean2]
dim(myTesting)
```

```{r, echo=TRUE}
dim(testing)
```

```{r,echo=TRUE}
for (i in 1:length(testing) ) {
        for(j in 1:length(myTraining)) {
        if( length( grep(names(myTraining[i]), names(testing)[j]) ) ==1)  {
            class(testing[j]) <- class(myTraining[i])
        }      
    }      
}
testing <- rbind(myTraining[2, -58] , testing) 
testing <- testing[-1,]
```

Decission Tree Alogrithm
```{r,echo=TRUE}
modFitA1 <- rpart(classe ~ ., data=myTraining, method="class")
```

```{r, echo=TRUE}
rpart.plot(modFitA1)
```

Prediction:
```{r, echo=TRUE}
predictionsA1 <- predict(modFitA1, myTesting, type = "class")
```

confusion Matrix
```{r, echo=TRUE}
confusionMatrix(predictionsA1, myTesting$classe)
```

Random Forest = Alogrith
```{r, echo=TRUE}
modFitB1 <- randomForest(classe ~. , data=myTraining)
```

Prediction:
```{r, echo=TRUE}
predictionsB1 <- predict(modFitB1, myTesting, type = "class")
```

Confusion Matrix
```{r,echo=TRUE}
confusionMatrix(predictionsB1, myTesting$classe)
```

##Findings
Random Forests yielded better Result

##Conclusion
```{r, echo=TRUE}
predictionsB2 <- predict(modFitB1, testing, type = "class")
```
